#!/bin/bash
byzanz-record -x 1 -y 41 -w 640 -h 480 test.gif --delay=2 -d 13
mkdir test
convert test.gif -scene 1 +adjoin test/frame_%03d.gif
rm test/frame_27*.gif test/frame_26[6789].gif
convert -delay 2 -loop 0 test/frame* test.gif
rm -r test
